server:
  port: 8088

logging:
  level:
    org.springframework: info

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  messages:
    basename: messages
#  security:
#    user:
#      name: username
#      password: passw0rd
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true # (2.5~) Hibernate 초기화 이후 data.sql 실행
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url:  jdbc:h2:tcp:localhost/~/restful
    username: sa
    password:

management:
  endpoints:
    web:
      exposure:
        include: "*"
